#!/usr/bin/bash

source "$DOTFILES_DIR/lib/utils"
MAIN_MODULE_DIR="$DOTFILES_DIR/modules/scripts"
CONFIG_DIR="$MAIN_MODULE_DIR/modules"
DEST_PATH="$HOME/.scripts"

log_info "Configuring scripts"

for script in "$CONFIG_DIR"/*; do
	if [[ -e "$script" ]]; then
		link_config "$script" "$DEST_PATH/$(basename "$script")"
	fi
done

log_success "Scripts configured successfully"
