#!/usr/bin/bash

source "$DOTFILES_DIR/lib/utils"

log_info "Configuring neovim"

MAIN_MODULE_DIR="$DOTFILES_DIR/modules/neovim"
CONFIG_DIR="$MAIN_MODULE_DIR/modules"
DEST_PATH="$HOME/.config/nvim"

link_dir () {
	from="$1"
	to="$2"

	mkdir -p "$to"
	if [ -n "$(ls -A "$from")" ]; then
		for file_path in "$from"/*; do
			file_name="$(basename "$file_path")"
			link_config "$file_path" "$to/$file_name"
		done
	fi
}

link_config "$CONFIG_DIR/init.lua" "$DEST_PATH/init.lua"
link_dir "$CONFIG_DIR/lua/config" "$DEST_PATH/lua/config"
link_dir "$CONFIG_DIR/lua/plugins" "$DEST_PATH/lua/plugins"

log_success "Neovim configured successfully"
