#!/usr/bin/bash

source "$DOTFILES_DIR/lib/utils"

log_info "Installing neovim"

core_install neovim luarocks git lua-language-server

if ! exists gopls; then
	go install golang.org/x/tools/gopls@latest
fi
pnpm i -g oxlint

log_success "Neovim installed successfully"
