#!/usr/bin/bash

source "$DOTFILES_DIR/lib/utils"

core_install base-devel xdg-desktop-portal bc tldr unzip man-pages man-db

sudo systemctl daemon-reload || log_error "Daemon reload failed, continuing..."

