#!/usr/bin/bash

source "$DOTFILES_DIR/lib/utils"

core_install \
	otf-montserrat inter-font ttf-input-nerd \ 
	ttf-jigmo noto-fonts-cjk ttf-nerd-fonts-symbols \
	noto-fonts-emoji

fc-cache -fv || log_error "Failed to update font cache." >&2

