#!/usr/bin/bash

export DEPENDENCIES_FILE_NAME="deps.txt"
export CONFIG_FILE_NAME="config"
export INSTALL_FILE_NAME="install"
export CONFIG_DIR_NAME="modules"

# Colors for output
export RED='\033[0;31m'
export GREEN='\033[0;32m'
export YELLOW='\033[1;33m'
export BLUE='\033[0;34m'
export NC='\033[0m' # No Color
