#!/usr/bin/bash

source "$DOTFILES_DIR/lib/utils"
MAIN_MODULE_DIR="$DOTFILES_DIR/modules/starship"
CONFIG_DIR="$MAIN_MODULE_DIR/modules"
DEST_PATH="$HOME/.config"

log_info "Configuring starship"

link_config "$CONFIG_DIR/starship.toml" "$DEST_PATH/starship.toml"

log_success "Starship configured successfully"
