#!/usr/bin/bash

source "$DOTFILES_DIR/lib/utils"
MAIN_MODULE_DIR="$DOTFILES_DIR/modules/kanata"
CONFIG_DIR="$MAIN_MODULE_DIR/modules"
DEST_PATH="$HOME/.config/kanata"

log_info "Configuring kanata"

link_config "$CONFIG_DIR/kanata.kbd" "$DEST_PATH/kanata.kbd"

log_success "Kanata configured successfully"
