#!/usr/bin/bash

source "$DOTFILES_DIR/lib/utils"

log_info "Configuring git"

MAIN_MODULE_DIR="$DOTFILES_DIR/modules/git"
CONFIG_DIR="$MAIN_MODULE_DIR/modules"
DEST_PATH="$HOME/.config/git"

link_config  "$CONFIG_DIR/config" "$DEST_PATH/config"

log_success "Git configured successfully"
